LinkIdProject/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('linkd.urls')),
]

linkd/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf.urls import url
from . import views
from django.conf.urls.static import static
from LinkIdProject import settings

app_name = 'linkd'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    #url(r'^(?P<string>[\w\-]+)$',views.index,name='indexsearch'),
    url(r'^search$',views.search,name='search'),
    url(r'^form$',views.form,name='form'),
    url(r'^readform$',views.readform,name='readform'),
    url(r'^getmentor/(?P<mentor_id>[0-9]+)$',views.getmentor,name='getmentor')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

linkd/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

INTEREST_AREAS = {
    'a': 'Android Development',
    'c': 'Computer Vision',
    'i': 'Information Security',
    'm': 'Machine Learning',
    'w': 'Web Development',
}


class Mentor(models.Model):
    mentor_name = models.CharField(max_length=50)
    mentor_github = models.CharField(max_length=1000)
    mentor_interest = models.CharField(max_length=20)
    mentor_emailid = models.CharField(max_length=100)

    def __str__(self):
        return self.mentor_name

    def interest_as_list(self):
        return list(self.mentor_interest)

linkd/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, get_object_or_404
from linkd.models import INTEREST_AREAS, Mentor
from django.http import HttpResponseRedirect
from django.urls import reverse
from difflib import SequenceMatcher


def index(request):
    try:
        search_query = request.POST['search']
        mList = []

        interest = max(INTEREST_AREAS.items(), key=lambda(k, v): SequenceMatcher(None, search_query, v).ratio())[0]

        mentors = Mentor.objects.filter(mentor_interest__contains=interest)
        for mentor in mentors:
            mList.append(mentor)
        return render(request, 'linkd/index.html', {'dictionary': INTEREST_AREAS, 'mlist': mList, 'query': search_query})
    except:
        return render(request, 'linkd/index.html', {'dictionary': INTEREST_AREAS})


def search(request):
    return HttpResponseRedirect(reverse('linkd:indexsearch', args=(request.POST['search'],)))


def readform(request):
    get_checked = request.POST.getlist('mentor_interest')
    mentor = Mentor(
        mentor_name=request.POST['mentor_name'],
        mentor_emailid=request.POST['mentor_emailid'],
        mentor_github=request.POST['mentor_github'],
        mentor_interest=''.join(get_checked)
    )
    mentor.save()
    return HttpResponseRedirect(reverse('linkd:getmentor', args=(mentor.pk,)))


def getmentor(request, mentor_id):
    mentor = get_object_or_404(Mentor, pk=mentor_id)
    return render(request, 'linkd/mentor.html', {
        'mentor': mentor,
        'dictionary': INTEREST_AREAS,
    })


def form(request):
    return render(request, 'linkd/form.html', {'dictionary': INTEREST_AREAS})

linkd/templates/linkd/footer.html
<div id="footer">
    &copy;&nbsp;Naveen 2017
</div>

linkd/templates/linkd/form.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'linkd/header.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'linkd/form.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'linkd/footer.css' %}">
</head>
<body>
{% include 'linkd/header.html' %}
<div id="main">
    <h2>Fill out this form.</h2>
    <form action="{% url 'linkd:readform' %}" method="post">
        {% csrf_token %}
        <label for="mentor_name">What is your name?</label><br>
        <input type="text" name="mentor_name" id="mentor_name"><br>
        <label for="mentor_email_id">Give us your email.</label><br>
        <input type="text" name="mentor_emailid" id="mentor_email_id"><br>
        <label for="github">Your github handle goes here.</label><br>
        <input type="text" name="mentor_github" id="github"><br>
        <p>Please Select your Interest</p>
        <div id="interestareas">
            {% for key,value in dictionary.items %}
            <input type="checkbox" name="mentor_interest" id="area{{ forloop.counter }}" value="{{ key }}">
            <label for="area{{ forloop.counter }}">
                {{ value }}
            </label><br>
            {% endfor %}
        </div>
        <input type="submit" name="Submit" value="Submit" id="submit">
    </form>
</div>
{% include 'linkd/footer.html' %}
</body>
</html>

linkd/templates/linkd/header.html
<ul id="head">
    <li><a href="{% url 'linkd:index' %}">link<span>ed</span></a></li>
    {% url 'linkd:form' as form_url%}<br/>
    {% if form_url != request.path %}
        <a href="{% url 'linkd:form' %}">REGISTER</a>
    {% endif %}
</ul>

linkd/templates/linkd/index.html
<!DOCTYPE html>
<!--Name<br>  mentor.mentor_name  <br>
EmailId<br>  mentor.mentor_emailid  <br>
Github<br>  mentor.mentor_github  <br>
Interests<br>
<ul>
     for value in mentor.mentor_interest
        <li>  dictionary|keyvalue:value  </li>
     endfor
</ul>-->
{% load staticfiles %}
{% load linkd_extras %}
<html>
<head>
    <link href="https://fonts.googleapis.com/css?family=Roboto:300" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'linkd/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'linkd/header.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'linkd/footer.css' %}">
</head>
<body>
<div>
    {% include 'linkd/header.html' %}
    <div id="main">
        <form action="{%url 'linkd:index'%}" method="post">
            {% csrf_token %}
            <div id="search">
                <input type="text" name="search" value="{{ query }}" placeholder="Enter keywords (e.g. android)">
                <input type="submit" name="submit" value="">
            </div>
        </form>
        {% if mlist %}
            <div id="cardcontainer">
                {% for mentor in mlist %}
                    <a href="{% url 'linkd:getmentor' mentor.pk %}">
                        <div class="card">
                            <div class="avatar" style="background-color:{% get_color %};">{{ mentor.mentor_name|first|upper }}</div>
                            <div class="label">{{ mentor.mentor_name }}</div>
                        </div>
                    </a><br/>
                {% endfor %}
            </div>
            {% else %}
            No matches found! Try another search
        {% endif %}
    </div>
    {% include 'linkd/footer.html' %}
</div>
</body>
</html>

linkd/templates/linkd/mentor.html
{% load linkd_extras %}

Name<br>{{mentor.mentor_name}}<br>
EmailId<br>{{mentor.mentor_emailid}}<br>
Github<br>{{mentor.mentor_github}}<br>
Interests<br>
<ul>
	{% for value in mentor.mentor_interest %}
		<li>{{dictionary|keyvalue:value}}</li>
	{% endfor %}
</ul>